#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from textwrap import dedent, indent

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, THIS_DIR)
from gen_pi_po import generate_header, parse_field_spec, parse_overrides  # noqa: E402


def parse_module_type(module_type: str):
    parts = [p for p in module_type.split('::') if p]
    if not parts:
        raise ValueError(f'invalid module type: {module_type}')
    if len(parts) == 1:
        return '', parts[0]
    return '::'.join(parts[:-1]), parts[-1]


def eval_pi_po_widths(cxx: str, include_dirs: list[str], cxxflags: list[str], defines: list[str],
                      generated_header_path: str, pi_po_ns: str) -> tuple[int, int]:
    with tempfile.TemporaryDirectory(prefix='eval_pi_po_widths_') as td:
        src = os.path.join(td, 'eval.cpp')
        exe = os.path.join(td, 'eval.out')
        with open(src, 'w', encoding='utf-8') as f:
            f.write(
                '#include <iostream>\n'
                f'#include "{generated_header_path}"\n'
                f'int main() {{ std::cout << static_cast<unsigned long long>({pi_po_ns}::PI_WIDTH) << "\\n"'
                f' << static_cast<unsigned long long>({pi_po_ns}::PO_WIDTH) << "\\n"; return 0; }}\n'
            )
        cmd = [cxx, '-std=c++17', '-O0', src, '-o', exe]
        for inc in include_dirs:
            cmd.extend(['-I', inc])
        for d in defines:
            cmd.append(f'-D{d}')
        cmd.extend(cxxflags)
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        out = subprocess.run([exe], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        vals = [int(x.strip(), 10) for x in out.stdout.splitlines() if x.strip()]
        if len(vals) != 2:
            raise RuntimeError(f'failed to evaluate PI/PO widths from {generated_header_path}')
        return vals[0], vals[1]


def generate_api_header(api_ns: str, function_name: str, use_c_linkage: bool,
                        pi_width_value: int, po_width_full_value: int,
                        export_po_begin: int, export_po_width: int | None) -> str:
    c_begin = c_end = ''
    if use_c_linkage:
        c_begin = '#ifdef __cplusplus\nextern "C" {\n#endif\n\n'
        c_end = '\n#ifdef __cplusplus\n}\n#endif\n'
    po_width_value = export_po_width if export_po_width is not None else po_width_full_value
    po_begin_comment = export_po_begin if export_po_width is not None else 0
    return dedent(f'''\
// Auto-generated by tools/gen_io_generator_so.py.
// Do not edit this file manually.
//
// Exported PO window configuration:
//   po_begin = {po_begin_comment}
//   po_width = {po_width_value}
//
#pragma once
#include <cstddef>
#include <cstdint>

// Full generalized-IO input width in bits.
static constexpr int PI_WIDTH = {pi_width_value};
// Full generalized-IO output width before any external slicing.
static constexpr int PO_WIDTH_FULL = {po_width_full_value};
// Exported output width seen by consumers of this header.
// If slicing is enabled during generation, this width corresponds to:
//   PO_full[po_begin : po_begin + PO_WIDTH)
static constexpr int PO_WIDTH = {po_width_value};

namespace {api_ns} {{
struct Context;
Context* context_create();
void context_destroy(Context* ctx);
void context_reset(Context* ctx);
void eval_comb(Context* ctx, const bool* pi, bool* po);
void eval_comb_range(Context* ctx, const bool* pi, bool* po, int po_begin, int po_width);
}} // namespace {api_ns}

{c_begin}// Evaluate the exported output vector seen by consumers.
// If slicing is enabled, `po` receives only the configured output window.
void {function_name}(bool *pi, bool *po);
// Evaluate an arbitrary sub-range from the full PO vector.
void {function_name}_range(bool *pi, bool *po, int po_begin, int po_width);
{c_end}
''')


def generate_api_cpp(module_header: str, generated_header: str, pi_po_ns: str, api_ns: str,
                     module_type: str, function_name: str, guard_specs: list[str],
                     export_po_begin: int, export_po_width: int | None) -> str:
    module_ns, class_name = parse_module_type(module_type)
    guard_lines = []
    for spec in guard_specs:
        # form: field_path:min:max
        field_path, min_s, max_s = spec.split(':', 2)
        guard_lines.append(
            dedent(
                f'''\
do {{
  auto _v = static_cast<long long>(ctx->module.io.{field_path});
  if (_v < {min_s}LL || _v > {max_s}LL) {{
    for (int i = 0; i < PO_WIDTH; ++i) {{
      po[i] = false;
    }}
    return;
  }}
}} while (0);'''
            )
        )
    guards = indent('\n'.join(guard_lines), '  ') if guard_lines else ''
    if export_po_width is None:
        direct_call = f'{api_ns}::eval_comb(&ctx, pi, po);'
        po_width_value = 'PO_WIDTH_FULL'
    else:
        direct_call = f'{api_ns}::eval_comb_range(&ctx, pi, po, {export_po_begin}, {export_po_width});'
        po_width_value = str(export_po_width)
    guard_block = f'\n{guards}\n' if guards else '\n'
    return dedent(f'''\
#include <algorithm>
#include <cstring>
#include "{module_header}"
#include "{generated_header}"
#include "{os.path.basename(generated_header).replace('_pi_po.h', '_api.h')}"

namespace {api_ns} {{
struct Context {{
  {module_type} module;
}};

Context* context_create() {{ return new Context(); }}
void context_destroy(Context* ctx) {{ delete ctx; }}
void context_reset(Context* ctx) {{ if (ctx) ctx->module.reset(); }}

void eval_comb(Context* ctx, const bool* pi, bool* po) {{
  if (!ctx || !pi || !po) return;
  {pi_po_ns}::unpack_pi(pi, ctx->module.io);{guard_block}  ctx->module.comb();
  {pi_po_ns}::pack_po(ctx->module.io, po);
}}

void eval_comb_range(Context* ctx, const bool* pi, bool* po, int po_begin, int po_width) {{
  if (!ctx || !pi || !po || po_begin < 0 || po_width < 0 || po_begin + po_width > PO_WIDTH_FULL) return;
  bool po_full[PO_WIDTH_FULL];
  std::memset(po_full, 0, sizeof(po_full));
  eval_comb(ctx, pi, po_full);
  std::memcpy(po, po_full + po_begin, static_cast<size_t>(po_width) * sizeof(bool));
}}
}} // namespace {api_ns}

void {function_name}(bool *pi, bool *po) {{
  thread_local {api_ns}::Context ctx;
  {direct_call}
}}

void {function_name}_range(bool *pi, bool *po, int po_begin, int po_width) {{
  thread_local {api_ns}::Context ctx;
  {api_ns}::eval_comb_range(&ctx, pi, po, po_begin, po_width);
}}
''')


def main(argv: list[str]) -> int:
    pre = argparse.ArgumentParser(add_help=False)
    pre.add_argument('--config')
    pre_args, _ = pre.parse_known_args(argv)
    config = {}
    if pre_args.config:
        with open(pre_args.config, 'r', encoding='utf-8') as f:
            config = json.load(f)

    ap = argparse.ArgumentParser(description='Generate pi/po header and dynamic-library wrapper, optionally build .so')
    ap.add_argument('--config')
    ap.add_argument('--header')
    ap.add_argument('--include', dest='include_path')
    ap.add_argument('--namespace', default='')
    ap.add_argument('--out-namespace', default='pi_po')
    ap.add_argument('--wrapper-type')
    ap.add_argument('--pi-field', action='append', default=[])
    ap.add_argument('--po-field', action='append', default=[])
    ap.add_argument('--override', action='append', default=[])
    ap.add_argument('--module-type')
    ap.add_argument('--module-header')
    ap.add_argument('--module-source', action='append', default=[])
    ap.add_argument('--guard-range', action='append', default=[])
    ap.add_argument('--api-namespace', default='io_generator_dl')
    ap.add_argument('--function-name', default='io_generator_outer')
    ap.add_argument('--export-po-begin', type=int, default=0)
    ap.add_argument('--export-po-width', type=int, default=None)
    ap.add_argument('--out-dir')
    ap.add_argument('--basename', default='auto_module')
    ap.add_argument('--c-linkage', action='store_true')
    ap.add_argument('--build-shared', action='store_true')
    ap.add_argument('--cxx', default='g++')
    ap.add_argument('--cxxflag', action='append', default=[])
    ap.add_argument('--include-dir', action='append', default=[])
    ap.add_argument('--define', action='append', default=[])
    if config:
        ap.set_defaults(**config)
    args = ap.parse_args(argv)
    required_keys = ['header', 'include_path', 'wrapper_type', 'module_type', 'module_header', 'out_dir']
    missing = [k for k in required_keys if not getattr(args, k)]
    if missing:
        ap.error('missing required arguments (or config keys): ' + ', '.join(missing))

    os.makedirs(args.out_dir, exist_ok=True)
    pi_po_h = os.path.join(args.out_dir, f'{args.basename}_pi_po.h')
    api_h = os.path.join(args.out_dir, f'{args.basename}_api.h')
    api_cpp = os.path.join(args.out_dir, f'{args.basename}_api.cpp')

    pi_po_text = generate_header(
        header_path=args.header,
        include_path=args.include_path,
        ns=args.namespace,
        out_ns=args.out_namespace,
        wrapper_type=args.wrapper_type,
        pi_fields=parse_field_spec(args.pi_field),
        po_fields=parse_field_spec(args.po_field),
        type_overrides=parse_overrides(args.override),
    )
    with open(pi_po_h, 'w', encoding='utf-8') as f:
        f.write(pi_po_text)

    pi_po_ns = f'{args.namespace}::{args.out_namespace}' if args.namespace else args.out_namespace
    eval_include_dirs = list(dict.fromkeys(args.include_dir + [args.out_dir]))
    pi_width_value, po_width_full_value = eval_pi_po_widths(
        args.cxx, eval_include_dirs, args.cxxflag, args.define, pi_po_h, pi_po_ns
    )
    with open(api_h, 'w', encoding='utf-8') as f:
        f.write(generate_api_header(args.api_namespace, args.function_name,
                                    args.c_linkage, pi_width_value, po_width_full_value,
                                    args.export_po_begin, args.export_po_width))
    with open(api_cpp, 'w', encoding='utf-8') as f:
        f.write(generate_api_cpp(args.module_header, os.path.basename(pi_po_h), pi_po_ns, args.api_namespace,
                                 args.module_type, args.function_name, args.guard_range,
                                 args.export_po_begin, args.export_po_width))

    print(pi_po_h)
    print(api_h)
    print(api_cpp)

    if args.build_shared:
        so_path = os.path.join(args.out_dir, f'lib{args.basename}.so')
        cmd = [args.cxx, '-shared', '-fPIC', '-O2', '-std=c++17', api_cpp] + args.module_source + ['-o', so_path]
        for inc in args.include_dir + [args.out_dir]:
            cmd.extend(['-I', inc])
        for d in args.define:
            cmd.append(f'-D{d}')
        cmd.extend(args.cxxflag)
        print('BUILD:', ' '.join(cmd))
        subprocess.run(cmd, check=True)
        print(so_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
